# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    campaignchain.job.operation.mailchimp.newsletter:
        class: CampaignChain\Operation\MailChimpBundle\Job\SendNewsletter
        arguments: [ @doctrine.orm.entity_manager, @service_container ]
    campaignchain.job.report.mailchimp.newsletter:
        class: CampaignChain\Operation\MailChimpBundle\Job\ReportSendNewsletter
        arguments: [ @doctrine.orm.entity_manager, @service_container ]
    campaignchain.operation.mailchimp.newsletter:
        class: CampaignChain\Operation\MailChimpBundle\EntityService\MailChimpNewsletter
        arguments: [ @doctrine.orm.entity_manager ]