# This file is part of the CampaignChain package.
#
# (c) Sandro Groganz <sandro@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
#    campaign_chain_operation_mail_chimp.example:
#        class: CampaignChain\Operation\MailChimpBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]